package interiores.presentation.swing.views.editor;

import interiores.business.controllers.DesignController;
import interiores.business.events.backtracking.ActualVariableSetEvent;
import interiores.business.events.backtracking.DebugSolveDesignStartedEvent;
import interiores.business.events.backtracking.NextValueEvent;
import interiores.business.events.backtracking.SolveDesignFinishedEvent;
import interiores.business.events.backtracking.ValueAssignedEvent;
import interiores.business.events.backtracking.ValueUnassignedEvent;
import interiores.business.models.Orientation;
import interiores.core.presentation.SwingController;
import interiores.core.presentation.annotation.Business;
import interiores.core.presentation.annotation.Listen;
import interiores.core.presentation.swing.SwingException;
import interiores.presentation.swing.views.map.RoomMapDebugger;
import java.awt.Point;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author hector
 */
@Business(DesignController.class)
public class RoomMapDebuggerFrame extends JFrame
{
    private DesignController designController;
    private RoomMapPanel debuggee;
    private RoomMapDebugger map;
    private int currentIteration;
    private int skipIterations;
    private boolean skipForever;
    private int drawIterations;
    private boolean isPaused;
    private boolean isFinished;
    private DefaultListModel variableListModel;
    
    /**
     * Creates new form RoomMapDebugger
     */
    public RoomMapDebuggerFrame(SwingController presentation) throws SwingException
    {
        this.designController = presentation.getBusinessController(DesignController.class);
        initComponents();
        
        isFinished = true;
    }
    
    public void setDebuggee(RoomMapPanel debuggee)
    {
        this.debuggee = debuggee;
        this.map = (RoomMapDebugger) debuggee.getRoomMap();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        actualVariableNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        currentIterationLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        orientationLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        variableList = new javax.swing.JList();
        iterateButton = new javax.swing.JButton();
        iterationsTextField = new javax.swing.JTextField();
        gridCheckBox = new javax.swing.JCheckBox();
        furnitureCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        resumePauseButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Room map debugger");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Actual variable:");

        actualVariableNameLabel.setText("Unknown");

        jLabel3.setText("Current iteration:");

        currentIterationLabel.setText("0");

        jLabel2.setText("Value information:");

        jLabel4.setText("Positon:");

        jLabel6.setText("Model:");

        jLabel7.setText("Orientation:");

        positionLabel.setText("Unknown");

        modelLabel.setText("Unknown");

        orientationLabel.setText("Unknown");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(currentIterationLabel))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actualVariableNameLabel))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(positionLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orientationLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modelLabel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(actualVariableNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(currentIterationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(positionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(modelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(orientationLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(variableList);

        iterateButton.setText("Iterate");
        iterateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                iterateButtonActionPerformed(evt);
            }
        });

        iterationsTextField.setText("1");

        gridCheckBox.setText("Show grid");
        gridCheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                gridCheckBoxActionPerformed(evt);
            }
        });

        furnitureCheckBox.setText("Show furniture");
        furnitureCheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                furnitureCheckBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Variable list:");

        resumePauseButton.setText("Resume");
        resumePauseButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                resumePauseButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                stopButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(iterationsTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iterateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gridCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(furnitureCheckBox))
                    .addComponent(resumePauseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(stopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resumePauseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gridCheckBox)
                    .addComponent(furnitureCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iterateButton)
                    .addComponent(iterationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iterateButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_iterateButtonActionPerformed
    {//GEN-HEADEREND:event_iterateButtonActionPerformed
        skipIterations = Integer.parseInt(iterationsTextField.getText());
        
        if(skipIterations < 1)
            skipIterations = 1;
        
        drawIterations = skipIterations / 10;
        
        if(drawIterations < 1)
            drawIterations = 1;
        
        else if(drawIterations > 100)
            drawIterations = 100;
        
        // Resume the solving!
        resume();
    }//GEN-LAST:event_iterateButtonActionPerformed

    private void gridCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_gridCheckBoxActionPerformed
    {//GEN-HEADEREND:event_gridCheckBoxActionPerformed
       if(gridCheckBox.isSelected())
           map.enableGrid();
       else
           map.disableGrid();
       
       debuggee.repaint();
    }//GEN-LAST:event_gridCheckBoxActionPerformed

    private void furnitureCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_furnitureCheckBoxActionPerformed
    {//GEN-HEADEREND:event_furnitureCheckBoxActionPerformed
        if(furnitureCheckBox.isSelected())
            map.enableDrawFurniture();
        else
            map.disableDrawFurniture();
        
        debuggee.repaint();
    }//GEN-LAST:event_furnitureCheckBoxActionPerformed

    private void resumePauseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resumePauseButtonActionPerformed
    {//GEN-HEADEREND:event_resumePauseButtonActionPerformed
        if(isPaused) {
            skipForever = true;
            drawIterations = 1000;
            
            resume();
        }
        else
            tryPause();
    }//GEN-LAST:event_resumePauseButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stopButtonActionPerformed
    {//GEN-HEADEREND:event_stopButtonActionPerformed
        tryPause();
        
        while(! designController.isSolverPaused())
            ;
        
        designController.stopSolver();
        map.clearFurniture();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
    {//GEN-HEADEREND:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualVariableNameLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel currentIterationLabel;
    private javax.swing.JCheckBox furnitureCheckBox;
    private javax.swing.JCheckBox gridCheckBox;
    private javax.swing.JButton iterateButton;
    private javax.swing.JTextField iterationsTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JLabel orientationLabel;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JButton resumePauseButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JList variableList;
    // End of variables declaration//GEN-END:variables

    @Listen(DebugSolveDesignStartedEvent.class)
    public void showDebug() {
        setVisible(true);
        
        if(isFinished)
           reset(); 
    }
    
    @Listen(ActualVariableSetEvent.class)
    public void actualVariableSet(ActualVariableSetEvent event)
    {
        String variableName = event.getVariableName();
        
        setActualVariableName(variableName);
        
        if(! variableListModel.contains(variableName))
            variableListModel.addElement(variableName);
        
        map.setActive(variableName);
    }
    
    @Listen(NextValueEvent.class)
    public void nextValue(NextValueEvent event)
    {
        updateCurrentIteration();
        updateValueInfo(event.getPosition(), event.getModelName(), event.getOrientation());
        
        map.addPoint(event.getPosition());
        
        if(skipForever || skipIterations > 1)
        {
            --skipIterations;
            
            while(! designController.isSolverPaused())
                ;
            
            designController.resumeSolver();
            
            if(skipIterations % drawIterations == 0)
                debuggee.repaint();
        }
        else
        {
            debuggee.repaint();
            pause();
        }
    }
    
    @Listen(ValueAssignedEvent.class)
    public void valueAssigned(ValueAssignedEvent event)
    {
        map.addFurniture(actualVariableNameLabel.getText(), event.getArea(), event.getModelColor(),
                event.getWholeArea());
        
        debuggee.repaint();
    }
    
    @Listen(ValueUnassignedEvent.class)
    public void valueUnassigned()
    {
        map.removeFurniture(actualVariableNameLabel.getText());
        
        debuggee.repaint();
    }
    
    @Listen(SolveDesignFinishedEvent.class)
    public void disableButtons() {
        pause();
        
        resumePauseButton.setEnabled(false);
        stopButton.setEnabled(false);
        iterateButton.setEnabled(false);
        closeButton.setEnabled(true);
        
        isFinished = true;
    }
    
    private void enableButtons() {
        pause();
        
        resumePauseButton.setEnabled(true);
        stopButton.setEnabled(true);
        iterateButton.setEnabled(true);
        closeButton.setEnabled(false);
        
    }
    
    public void reset()
    {
        map.clear();
        
        gridCheckBox.setSelected(map.isGridEnabled());
        furnitureCheckBox.setSelected(map.shouldDrawFurniture());
        
        setActualVariableName("Unknown");
        variableListModel = new DefaultListModel();
        variableList.setModel(variableListModel);
        
        skipIterations = drawIterations = 1;
        skipForever = false;
        resetCurrentIteration();
        setValueInfo("Unknown", "Unknown", "Unknown");
        
        enableButtons();
        
        isFinished = false;
    }
    
    private void setActualVariableName(String variableName)
    {
        actualVariableNameLabel.setText(variableName);
    }
        
    private void updateCurrentIteration()
    {
        setCurrentIteration(currentIteration + 1);
    }
    
    private void resetCurrentIteration()
    {
        setCurrentIteration(0);
    }
    
    private void setCurrentIteration(int iteration)
    {
        currentIteration = iteration;
        currentIterationLabel.setText(String.valueOf(iteration));
    }
    
    private void updateValueInfo(Point position, String modelName, Orientation orientation)
    {
        setValueInfo("(" + (int)position.getX() + ", " + (int)position.getY() + ")", modelName,
                orientation.toString(true));
    }
    
    private void setValueInfo(String position, String modelName, String orientation)
    {
        positionLabel.setText(position);
        modelLabel.setText(modelName);
        orientationLabel.setText(orientation);
    }
    
    private void pause() {
        setIsPaused(true);
    }
    
    private void tryPause() {
        skipForever = false;
        skipIterations = 1;
    }
    
    private void resume() {
        setIsPaused(false);
        designController.resumeSolver();
    }
    
    private void setIsPaused(boolean isPaused) {
        this.isPaused = isPaused;
        
        resumePauseButton.setText(isPaused ? "Resume" : "Pause");
    }
}
