/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interiores.presentation.swing.views.catalogs;

import interiores.business.controllers.FurnitureTypeController;
import interiores.core.Debug;
import java.awt.event.KeyEvent;
import java.util.Collection;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author larribas
 */
public class PlaceFTDialog extends javax.swing.JDialog {

    private String furnitureName;
    
    private FurnitureTypeController ftController;
    
    final DefaultListModel model = new DefaultListModel();
    
    /**
     * Creates new form PlaceFTDialog
     */
    public PlaceFTDialog(FurnitureTypeController ftc, String fname) {

        furnitureName = fname;
        ftController = ftc;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        placingList = new javax.swing.JList();
        placingSelector = new javax.swing.JComboBox();
        furnitureSelector = new javax.swing.JComboBox();
        newButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select placement options");
        setAlwaysOnTop(true);

        dialogTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        dialogTitle.setText("Place " + furnitureName);

        placingList.setModel(model);
        placingList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                placingListKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(placingList);
        HashMap<String,String> pcs = ftController.getPlacementConstraints(furnitureName);
        for (String f : pcs.keySet()) model.addElement(fromSlang(pcs.get(f)) + " " + f);

        placingSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Next to", "Away from", "In front of" }));

        ImageIcon im = new javax.swing.ImageIcon("src/resources/add_element.png");
        im.setImage( im.getImage().getScaledInstance(25,25,java.awt.Image.SCALE_SMOOTH) );
        newButton.setIcon(im); // NOI18N
        newButton.setBorder(BorderFactory.createEmptyBorder());
        newButton.setContentAreaFilled(false);
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(okButton)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(layout.createSequentialGroup()
                            .add(placingSelector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(18, 18, 18)
                            .add(furnitureSelector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(18, 18, 18)
                            .add(newButton))
                        .add(dialogTitle)
                        .add(jScrollPane1)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(dialogTitle)
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(placingSelector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(furnitureSelector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(newButton))
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(okButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Collection<String> furn = ftController.getFullNamesMap().values();
        furn.remove(furnitureName);
        String[] f = furn.toArray(new String[0]);
        furnitureSelector.setModel(new javax.swing.DefaultComboBoxModel(f));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        String pc = (String) placingSelector.getSelectedItem();
        String internal_pc = toSlang(pc);
        String otherFurniture = (String) furnitureSelector.getSelectedItem();
        ftController.addPlacementConstraint(internal_pc, furnitureName, otherFurniture);
        addToModel(pc,otherFurniture);
        Debug.println("Adding placement constraint: " + furnitureName + " should be " + pc + " " + otherFurniture);
    }//GEN-LAST:event_newButtonActionPerformed

    private void placingListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placingListKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_DELETE ) {
            String f = (String) placingList.getSelectedValue();
            int lf = f.length();
            f = f.substring(f.lastIndexOf(" "),lf);
            ftController.removePlacementConstraint(furnitureName,f);
            model.remove(placingList.getSelectedIndex());
            Debug.println("Removing placement constraint: " + furnitureName + " isn't affected by " + f);
        }
            
    }//GEN-LAST:event_placingListKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dialogTitle;
    private javax.swing.JComboBox furnitureSelector;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newButton;
    private javax.swing.JButton okButton;
    private javax.swing.JList placingList;
    private javax.swing.JComboBox placingSelector;
    // End of variables declaration//GEN-END:variables

    /**
     * Translates "Next to" into "next-to", and likewise for any other placement constraint
     */
    private String toSlang(String pc) {
        String translation = pc.toLowerCase();
        translation = translation.replace(" ", "-");
        return translation;
    }
    
    private String fromSlang(String pc) {
        String translation = pc.replace("-"," ");
        char firstLetter = Character.toUpperCase(translation.charAt(0) );
        return firstLetter + translation.substring(1);
    }
    
    private void addToModel(String pc, String otherFurniture) {
        for (int i = 0; i < model.size(); i++)
            if (( (String) model.getElementAt(i) ).contains(otherFurniture)) {
                model.setElementAt(pc + " " + otherFurniture, i); return;
            }
        model.addElement(pc + " " + otherFurniture);
    }




}
