package interiores.presentation.swing.views;

import interiores.presentation.swing.views.catalogs.FurnitureTypeCatalogFrame;
import interiores.presentation.swing.views.catalogs.RoomTypeCatalogFrame;
import interiores.presentation.swing.views.catalogs.FurnitureModelCatalogFrame;
import help.HelpView;
import interiores.business.controllers.RoomController;
import interiores.business.events.room.RoomCreatedEvent;
import interiores.business.events.room.RoomLoadedEvent;
import interiores.core.presentation.SwingController;
import interiores.core.presentation.annotation.Listen;
import interiores.core.presentation.swing.SwingException;
import interiores.presentation.swing.helpers.FileChooser;
import java.awt.BorderLayout;
import java.awt.Component;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.xml.bind.JAXBException;

/**
 *
 * @author hector
 */
public class MainAppFrame extends JFrame
{
    private static int TOOLS_INDEX = 2;
    
    private SwingController presentation;
    private RoomController roomController;
    private WelcomePanel welcome;
    private TerminalPanel terminal;
    private MapEditorPanel editorPanel;
    
    private List<Component> previousViews, currentViews;
    private JFileChooser fileChooser;
    
    private boolean toolsEnabled = false;
    
    /**
     * Creates new form MainView
     */
    public MainAppFrame(SwingController presentation) throws SwingException
    {
        initComponents();
        setLayout(new BorderLayout());
        
        this.presentation = presentation;
        roomController = presentation.getBusinessController(RoomController.class);
        welcome = presentation.get(WelcomePanel.class);
        terminal = presentation.get(TerminalPanel.class);
        
        previousViews = new ArrayList();
        currentViews = new ArrayList();
        
        fileChooser = new FileChooser();

               
        loadComponent(welcome, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newRoom = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        rtcMenuItem = new javax.swing.JMenuItem();
        ftcMenuItem = new javax.swing.JMenuItem();
        fmcMenuItem = new javax.swing.JMenuItem();
        
        jMenu3 = new javax.swing.JMenu();
        terminalMenuCheckbox = new javax.swing.JCheckBoxMenuItem();
        helpMenu = new javax.swing.JMenu();
        generalHelpMenu = new javax.swing.JMenuItem();
        terminalHelpMenu = new javax.swing.JMenuItem();
        aboutHelpMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interior design");
        setAlwaysOnTop(true);
        setResizable(false);

        jMenu1.setText("File");

        newRoom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newRoom.setText("New room design...");
        newRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRoomActionPerformed(evt);
            }
        });
        jMenu1.add(newRoom);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open room design...");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Save room design...");
        saveMenuItem.setEnabled(false);
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        menuBar.add(jMenu1);

        jMenu2.setText("Edit");

        rtcMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        rtcMenuItem.setText("Room types catalog");
        rtcMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtcMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(rtcMenuItem);

        ftcMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        ftcMenuItem.setText("Furniture types catalog");
        ftcMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftcMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ftcMenuItem);

        fmcMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        fmcMenuItem.setText("Furniture models catalog");
        fmcMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmcMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(fmcMenuItem);

        menuBar.add(jMenu2);

        jMenu3.setText("View");
        jMenu3.setName("View"); // NOI18N

        terminalMenuCheckbox.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        terminalMenuCheckbox.setText("Terminal");
        terminalMenuCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminalMenuCheckboxActionPerformed(evt);
            }
        });
        jMenu3.add(terminalMenuCheckbox);

        menuBar.add(jMenu3);

        helpMenu.setText("Help");

        generalHelpMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        generalHelpMenu.setText("General");
        generalHelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalHelpMenuActionPerformed(evt);
            }
        });
        helpMenu.add(generalHelpMenu);

        terminalHelpMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        terminalHelpMenu.setText("Terminal");
        terminalHelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminalHelpMenuActionPerformed(evt);
            }
        });
        helpMenu.add(terminalHelpMenu);

        aboutHelpMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        aboutHelpMenu.setText("About");
        helpMenu.add(aboutHelpMenu);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newRoomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newRoomActionPerformed
    {//GEN-HEADEREND:event_newRoomActionPerformed
        presentation.showNew(NewDesignDialog.class);
    }//GEN-LAST:event_newRoomActionPerformed

    private void rtcMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtcMenuItemActionPerformed
        presentation.showNew(RoomTypeCatalogFrame.class);
    }//GEN-LAST:event_rtcMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitMenuItemActionPerformed
    {//GEN-HEADEREND:event_exitMenuItemActionPerformed
        // @TODO Confirmation if design has changes
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openMenuItemActionPerformed
    {//GEN-HEADEREND:event_openMenuItemActionPerformed
        openDesign();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveMenuItemActionPerformed
    {//GEN-HEADEREND:event_saveMenuItemActionPerformed
        int status = fileChooser.showSaveDialog(this);
        
        if(status == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            
            try {
                roomController.save(file.getAbsolutePath());
            }
            catch(JAXBException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_saveMenuItemActionPerformed


    private void ftcMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftcMenuItemActionPerformed
        presentation.showNew(FurnitureTypeCatalogFrame.class);
    }//GEN-LAST:event_ftcMenuItemActionPerformed

    private void fmcMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmcMenuItemActionPerformed
        presentation.showNew(FurnitureModelCatalogFrame.class);
    }//GEN-LAST:event_fmcMenuItemActionPerformed

   
    private void terminalMenuCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminalMenuCheckboxActionPerformed
        if(terminalMenuCheckbox.isSelected())
            loadComponent(terminal, BorderLayout.PAGE_END);
        else
            unloadComponent(terminal);
    }//GEN-LAST:event_terminalMenuCheckboxActionPerformed

private void generalHelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalHelpMenuActionPerformed
    HelpView helpFrame = presentation.getNew(HelpView.class);
    helpFrame.load("gui/guia-gui.html", "Guia");
}//GEN-LAST:event_generalHelpMenuActionPerformed

private void terminalHelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminalHelpMenuActionPerformed
    HelpView helpFrame = presentation.getNew(HelpView.class);
    helpFrame.load("terminal/node1.html", "Terminal Manual");
}//GEN-LAST:event_terminalHelpMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutHelpMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem fmcMenuItem;
    private javax.swing.JMenuItem ftcMenuItem;
    private javax.swing.JMenuItem generalHelpMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newRoom;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem rtcMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem terminalHelpMenu;
    private javax.swing.JCheckBoxMenuItem terminalMenuCheckbox;
    // End of variables declaration//GEN-END:variables

    
    // PANEL LOADING. Event listeners
    // showTopology() :  Shows the topology view
    // showFurnitureAndMap() :  Shows the dual furniture-selection + map view
    // showDesigns() :  Shows the designs view (all the generated designs)
    // showAlternate(view) : Shows an alternate view (that is, a view whose meaning
    //                       is independent from from the main use case, and from which,
    //                       therefore, we should return to the previous view
    
    public void openDesign() {
        int status = fileChooser.showOpenDialog(this);
        
        if(status == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            
            try {
                roomController.load(file.getAbsolutePath());
            }
            catch(JAXBException e) {
                e.printStackTrace();
            }
        }
    }
    
    @Listen({RoomCreatedEvent.class, RoomLoadedEvent.class})
    public void showFurnitureAndMap() {
        unloadComponent(welcome);
        
        MapEditorPanel editorPanel = presentation.getNew(MapEditorPanel.class);
        loadComponent(editorPanel, BorderLayout.CENTER);
        
        saveMenuItem.setEnabled(true);
        
        if(toolsEnabled)
            menuBar.remove(TOOLS_INDEX);
        else
            toolsEnabled = true;
        
        menuBar.add(editorPanel.getToolsMenu(), TOOLS_INDEX);

    }
    
    private void unloadCurrentView() {
        previousViews.clear();
        for (Component c : currentViews) {
            c.setVisible(false);
            previousViews.add(c);
        }
        currentViews.clear();
    }
    
    
    protected void loadPreviousView() {
        for (Component c : currentViews) remove(c);
        currentViews.clear();
        
        for (Component c : previousViews) {
            currentViews.add(c);
            c.setVisible(true);
        }
        previousViews.clear();
        
        invalidate();
        validate();
        pack();
    }
    
    private void loadComponent(Component comp, Object constraints) {
        add(comp, constraints);
        currentViews.add(comp);
        comp.setVisible(true);
        
        invalidate();
        validate();
        pack();
    }
    
    private void unloadComponent(Component comp) {
        remove(comp);
        
        invalidate();
        validate();
        pack();
    }
    
}
