package interiores.presentation.swing.views;

import interiores.business.events.room.RoomCreatedEvent;
import interiores.business.events.room.RoomLoadedEvent;
import interiores.core.Debug;
import interiores.core.presentation.SwingController;
import interiores.core.presentation.annotation.Listen;
import interiores.core.presentation.swing.SwingException;
import java.awt.BorderLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author hector
 */
public class MainAppFrame extends JFrame
{
    private SwingController presentation;
    private WelcomePanel welcome;
    private RoomMapPanel map;
    private WishListPanel wishListPanel;
    private RoomTypeCatalogPanel rtCatalogPanel;
    
    private List<Component> previousViews;
    
    /**
     * Creates new form MainView
     */
    public MainAppFrame(SwingController presentation) throws SwingException
    {
        initComponents();
        setLayout(new BorderLayout());
        
        this.presentation = presentation;
        previousViews = new ArrayList();
        welcome = presentation.get(WelcomePanel.class);
        map = presentation.get(RoomMapPanel.class);
        wishListPanel = presentation.get(WishListPanel.class);
        rtCatalogPanel = presentation.get(RoomTypeCatalogPanel.class);
        
        loadComponent(welcome, BorderLayout.CENTER);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newRoom = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        rtCatalog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interior design");
        setAlwaysOnTop(true);

        jMenu1.setText("File");

        newRoom.setText("New room design...");
        newRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRoomActionPerformed(evt);
            }
        });
        jMenu1.add(newRoom);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        rtCatalog.setText("Room type catalog");
        rtCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtCatalogActionPerformed(evt);
            }
        });
        jMenu2.add(rtCatalog);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newRoomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newRoomActionPerformed
    {//GEN-HEADEREND:event_newRoomActionPerformed
        presentation.showNew(NewDesignDialog.class);
    }//GEN-LAST:event_newRoomActionPerformed

    private void rtCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtCatalogActionPerformed
        //remove(welcome);
        add(rtCatalogPanel);
        rtCatalogPanel.setVisible(true);
        validate();
        pack();
    }//GEN-LAST:event_rtCatalogActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem newRoom;
    private javax.swing.JMenuItem rtCatalog;
    // End of variables declaration//GEN-END:variables

    
    // PANEL LOADING. Event listeners
    // showTopology() :  Shows the topology view
    // showFurnitureAndMap() :  Shows the dual furniture-selection + map view
    // showDesigns() :  Shows the designs view (all the generated designs)
    // showAlternate(view) : Shows an alternate view (that is, a view whose meaning
    //                       is independent from from the main use case, and from which,
    //                       therefore, we should return to the previous view
    
    
    
    
    
    @Listen({RoomCreatedEvent.class, RoomLoadedEvent.class})
    public void showFurnitureAndMap() {
        unloadCurrentView(false);
        loadComponent(map, BorderLayout.CENTER);
        loadComponent(wishListPanel, BorderLayout.LINE_END);
        wishListPanel.updateSelectable();
        wishListPanel.updateSelected();
        validate();
        pack();
        printComponents();
    }
    
    private void unloadCurrentView(boolean thoroughly) {
        for (Component c : previousViews) {
            if (thoroughly) remove(c);
            else c.setVisible(false);
        }
    }
    
    private void loadComponent(Component comp, Object constraints) {
        add(comp, constraints);
        previousViews.add(comp);
        comp.setVisible(true);
    }
    
    
    private void printComponents() {
        Debug.println("Components in the container: " + getComponentCount());
        for (Component c : getComponents())
            Debug.println("Component: " + c.toString());
    }
}
