package interiores.presentation.swing.views;

import interiores.business.controllers.RoomController;
import interiores.business.events.room.RoomCreatedEvent;
import interiores.business.events.room.RoomLoadedEvent;
import interiores.core.Debug;
import interiores.core.presentation.SwingController;
import interiores.core.presentation.annotation.Listen;
import interiores.core.presentation.swing.SwingException;
import interiores.presentation.swing.helpers.FileChooser;
import java.awt.BorderLayout;
import java.awt.Component;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.xml.bind.JAXBException;

/**
 *
 * @author hector
 */
public class MainAppFrame extends JFrame
{
    private SwingController presentation;
    private RoomController roomController;
    private WelcomePanel welcome;
    private TerminalPanel terminal;
    private RoomTypeCatalogPanel rtCatalogPanel;
    
    private List<Component> previousViews, currentViews;
    private JFileChooser fileChooser;
    
    /**
     * Creates new form MainView
     */
    public MainAppFrame(SwingController presentation) throws SwingException
    {
        initComponents();
        setLayout(new BorderLayout());
        
        this.presentation = presentation;
        roomController = presentation.getBusinessController(RoomController.class);
        welcome = presentation.get(WelcomePanel.class);
        terminal = presentation.get(TerminalPanel.class);
        rtCatalogPanel = presentation.get(RoomTypeCatalogPanel.class);
        
        previousViews = new ArrayList();
        currentViews = new ArrayList();
        
        fileChooser = new FileChooser();

        loadComponent(welcome, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newRoom = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        rtCatalog = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        terminalMenuCheckbox = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interior design");
        setAlwaysOnTop(true);
        setResizable(false);

        jMenu1.setText("File");

        newRoom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newRoom.setText("New room design...");
        newRoom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newRoomActionPerformed(evt);
            }
        });
        jMenu1.add(newRoom);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open room design...");
        openMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                openMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Save room design...");
        saveMenuItem.setEnabled(false);
        saveMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        rtCatalog.setText("Room type catalog");
        rtCatalog.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rtCatalogActionPerformed(evt);
            }
        });
        jMenu2.add(rtCatalog);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        terminalMenuCheckbox.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        terminalMenuCheckbox.setText("Terminal");
        terminalMenuCheckbox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                terminalMenuCheckboxActionPerformed(evt);
            }
        });
        jMenu3.add(terminalMenuCheckbox);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newRoomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newRoomActionPerformed
    {//GEN-HEADEREND:event_newRoomActionPerformed
        presentation.showNew(NewDesignDialog.class);
    }//GEN-LAST:event_newRoomActionPerformed

    private void rtCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtCatalogActionPerformed
        unloadCurrentView();
        loadComponent(rtCatalogPanel, BorderLayout.CENTER);      
    }//GEN-LAST:event_rtCatalogActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitMenuItemActionPerformed
    {//GEN-HEADEREND:event_exitMenuItemActionPerformed
        // @TODO Confirmation if design has changes
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openMenuItemActionPerformed
    {//GEN-HEADEREND:event_openMenuItemActionPerformed
        openDesign();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveMenuItemActionPerformed
    {//GEN-HEADEREND:event_saveMenuItemActionPerformed
        int status = fileChooser.showSaveDialog(this);
        
        if(status == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            
            try {
                roomController.save(file.getAbsolutePath());
            }
            catch(JAXBException e) {
                
            }
        }
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void terminalMenuCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminalMenuCheckboxActionPerformed
        if(terminalMenuCheckbox.isSelected())
            loadComponent(terminal, BorderLayout.PAGE_END);
        else
            unloadComponent(terminal);
    }//GEN-LAST:event_terminalMenuCheckboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem newRoom;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem rtCatalog;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JCheckBoxMenuItem terminalMenuCheckbox;
    // End of variables declaration//GEN-END:variables

    
    // PANEL LOADING. Event listeners
    // showTopology() :  Shows the topology view
    // showFurnitureAndMap() :  Shows the dual furniture-selection + map view
    // showDesigns() :  Shows the designs view (all the generated designs)
    // showAlternate(view) : Shows an alternate view (that is, a view whose meaning
    //                       is independent from from the main use case, and from which,
    //                       therefore, we should return to the previous view
    
    public void openDesign() {
        int status = fileChooser.showOpenDialog(this);
        
        if(status == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            
            try {
                roomController.load(file.getAbsolutePath());
            }
            catch(JAXBException e) {
                
            }
        }
    }
    
    @Listen({RoomCreatedEvent.class, RoomLoadedEvent.class})
    public void showFurnitureAndMap() {
        unloadComponent(welcome);
        
        saveMenuItem.setEnabled(true);
        
        RoomMapPanel map = presentation.getNew(RoomMapPanel.class);
        WishListPanel wishListPanel = presentation.getNew(WishListPanel.class);
        
        loadComponent(map, BorderLayout.CENTER);
        loadComponent(wishListPanel, BorderLayout.LINE_END);
    }
    
    private void unloadCurrentView() {
        for (Component c : currentViews) {
            remove(c);
            c.setVisible(false);
            previousViews.add(c);
        }
        currentViews.clear();
    }
    
    private void loadComponent(Component comp, Object constraints) {
        add(comp, constraints);
        currentViews.add(comp);
        comp.setVisible(true);
        
        invalidate();
        validate();
        pack();
    }
    
    private void unloadComponent(Component comp) {
        remove(comp);
        
        invalidate();
        validate();
        pack();
    }
    
    
    private void printComponents() {
        Debug.println("Components in the container: " + getComponentCount());
        for (Component c : getComponents())
            Debug.println("Component: " + c.toString());
    }
}
