package interiores.presentation.swing.views;

import interiores.business.controllers.RoomController;
import interiores.business.controllers.RoomTypeController;
import interiores.core.presentation.SwingController;
import interiores.utils.Range;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author hector
 */
public class NewDesignDialog extends JDialog
{
    private SwingController swing;
    private RoomController roomController;
    private RoomTypeController roomTypesController;
    private Map<String, String> roomTypes;
    
    public NewDesignDialog(SwingController presentation) {
        initComponents();
        
        this.setModalityType(ModalityType.APPLICATION_MODAL);
        this.swing = presentation;
        
        roomController = swing.getBusinessController(RoomController.class);
        roomTypesController = swing.getBusinessController(RoomTypeController.class);
        roomTypes = roomTypesController.getFullNamesMap();
        
        for(String fullName : roomTypes.keySet())
            roomTypesList.addItem(fullName);
        
        updateSpinners();
    }
    
    private void updateSpinners() {
        String value = (String) roomTypesList.getSelectedItem();
        
        if(value == null)
            return;
        
        widthField.setEnabled(true);
        depthField.setEnabled(true);
        newDesignButton.setEnabled(true);
        
        String typeId = roomTypes.get(value);
        
        Range widthRange = roomTypesController.getWidthRange(typeId);
        Range depthRange = roomTypesController.getDepthRange(typeId);
        
        setSpinnerModel(widthField, widthRange);
        setSpinnerModel(depthField, depthRange);
    }
    
    private void setSpinnerModel(JSpinner spinner, Range range) {
        int value = (Integer) spinner.getValue();
        
        if(value < range.min) value = range.min;
        else if(value > range.max) value = range.max;
        
        spinner.setModel(new SpinnerNumberModel(value, range.min, range.max, roomController.getResolution()));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roomTypesList = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        newDesignButton = new javax.swing.JButton();
        widthField = new javax.swing.JSpinner();
        depthField = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create a new room design...");
        setAlwaysOnTop(true);

        jLabel1.setText("Width:");

        jLabel2.setText("Depth:");

        jLabel3.setText("Type:");

        roomTypesList.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                roomTypesListActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        newDesignButton.setText("New design");
        newDesignButton.setEnabled(false);
        newDesignButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newDesignButtonActionPerformed(evt);
            }
        });

        widthField.setEnabled(false);

        depthField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomTypesList, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(widthField)
                            .addComponent(depthField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(newDesignButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTypesList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(widthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(depthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(newDesignButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void roomTypesListActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_roomTypesListActionPerformed
    {//GEN-HEADEREND:event_roomTypesListActionPerformed
        updateSpinners();
    }//GEN-LAST:event_roomTypesListActionPerformed

    private void newDesignButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newDesignButtonActionPerformed
    {//GEN-HEADEREND:event_newDesignButtonActionPerformed
        String typeId = roomTypes.get((String)roomTypesList.getSelectedItem());
        int width = (Integer) widthField.getValue();
        int depth = (Integer) depthField.getValue();
        
        roomController.create(typeId, width, depth);
        dispose();
    }//GEN-LAST:event_newDesignButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner depthField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton newDesignButton;
    private javax.swing.JComboBox roomTypesList;
    private javax.swing.JSpinner widthField;
    // End of variables declaration//GEN-END:variables
}
