package interiores.presentation.swing.views;

import interiores.presentation.swing.SwingPanel;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author hector
 */
public class RoomMapPanel extends SwingPanel
{

    /**
     * Creates new form RoomMap
     */
    public RoomMapPanel()
    {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        g.setColor(Color.white);
        g.fillRect(0, 0, 800, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
