package interiores.presentation.swing.views;

import interiores.core.presentation.SwingController;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author hector
 */
public class RoomMapFrame extends JFrame
{
    /**
     * Creates new form RoomMap
     */
    public RoomMapFrame(SwingController presentation) throws Exception
    {
        initComponents();
        setLayout(new BorderLayout());
        
        add(presentation.get(RoomMapPanel.class), BorderLayout.CENTER);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Room map");
        setAlwaysOnTop(true);
        setResizable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
