package interiores.presentation.swing.views;

import interiores.business.models.OrientedRectangle;
import interiores.business.models.backtracking.FurnitureValue;
import interiores.core.Debug;
import interiores.core.presentation.annotation.Event;
import interiores.presentation.swing.SwingPanel;
import interiores.presentation.swing.views.map.GridMap;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Map;
import java.util.Map.Entry;

/**
 *
 * @author hector
 */
public class RoomMapPanel extends SwingPanel
{
    private GridMap map;

    /**
     * Creates new form RoomMap
     */
    public RoomMapPanel()
    {
        map = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void paintComponent(Graphics g)
    {
        if(map != null) {
            Graphics2D g2d = (Graphics2D) g;
            map.draw(g2d);
        }
    }
    
    @Event(paramNames = {"width", "depth"})
    public void roomCreated(int width, int depth)
    {
        map = new GridMap(width, depth);
        
        if(Debug.isEnabled())
            map.enableGrid();
        
        setPreferredSize(new Dimension(map.getWidth(), map.getHeight()));  
    }
    
    @Event(paramNames = {"width", "depth"})
    public void roomLoaded(int width, int depth)
    {
        roomCreated(width, depth);
    }
    
    @Event(paramNames = {"design"})
    public void roomDesigned(Map<String, FurnitureValue> design) {
        map.clear();
        
        for(Entry<String, FurnitureValue> entry : design.entrySet()) {
            String name = entry.getKey();
            Color color = entry.getValue().getModel().getColor();
            
            furnitureAdded(name, entry.getValue().getArea(), color);
        }
        
        repaint();
    }
    
    @Event(paramNames = {"name", "x", "y", "width", "depth", "orientation"})
    public void furnitureAdded(String name, OrientedRectangle area, Color color) {
        map.addFurniture(name, area, color);
    }
    
    @Event(paramNames = {"isFound"})
    public void designFinished(boolean isFound) {
        if (isFound) map.setStatus("Solution found! :)");
        else map.setStatus("Solution not found :(");
        
        repaint();
    }
    
    @Event
    public void designStarted() {
        map.setStatus("Searching...");
        
        repaint();
    }
    
}
